import type { Metadata } from "next";
import { Anton, Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/footer/footer";
import { Slide, ToastContainer } from "react-toastify";
import { AuthProvider } from "@/context/AuthContext";
import 'leaflet/dist/leaflet.css';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const anton = Anton({
  variable: "--font-anton",
  subsets: ["latin"],
  weight: ["400"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "FitHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className="h-full">
      {/* 👇 el body define la grilla: header | contenido | footer */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${anton.variable} ${poppins.variable} antialiased min-h-screen grid grid-rows-[auto_1fr_auto] m-0`}
      >
        <AuthProvider>
          <Navbar />
          <main className="flex-1">{children}</main>

          <Footer />
          <ToastContainer
            position="bottom-center"
            autoClose={2000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick={false}
            rtl={false}
            pauseOnFocusLoss={false}
            draggable={false}
            pauseOnHover={false}
            theme="dark"
            transition={Slide}
          />
        </AuthProvider>
      </body>
    </html>
  );
}
